[package]
name = "wait-for-internet"
version = "0.1.3"
edition = "2018"
authors = ["Sean Breckenridge <seanbrecke@gmail.com>"]
license = "MIT"
description = "Command line utility that waits till you have an internet connection."
readme = "README.md"
homepage = "https://gitlab.com/seanbreckenridge/wait-for-internet"
repository = "https://gitlab.com/seanbreckenridge/wait-for-internet"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.3"
online = "0.2.2"
spinners = "1.2.0"
